apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-demo
  template:
    metadata:
      labels:
        app: django-demo
    spec:
      containers:
      - name: django-demo
        image: ghcr.io/obi228/k3s-demo-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"