apiVersion: v1
kind: Service
metadata:
  name: django-demo
  namespace: default
spec:
  type: NodePort
  selector:
    app: django-demo
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080